javascript: (function() {
    var f = ["Bùi", "Cao", "Chu", "Chung", "Chuong", "Cù", "Diệp", "Doăn", "Duong", "Đào", "Đặng", "Đâu", "Đinh", "Điền", "Đoàn", "Đê", "Dung", "Giang", "Giao", "Giáp", "Giá", "Hoàng", "Huỳnh", "Hà", "Hương", "Hoan", "Hưng", "Hòa", "Khuong", "Khang", "Kim", "Kiều", "La", "Le", "Lê", "Lô", "Lư", "Luu", "Luong", "Mai", "Mận", "Nguyên", "Nông", "Ông", "Phan", "Phùng", "Phuong", "Phạm", "Quách", "Thái", "Tiêu", "Triệu", "Truong", "Trần", "Tranh", "Tô", "Tăng", "Tú", "Toản", "Tạ", "Văn", "Vu", "Vuong"],
        l = ["An", "Anh", "B́ình", "Bích", "Bang", "Bách", "Bao", "Bảo", "Ca", "Chi", "Chinh", "Chiêu", "Chung", "Châu", "Cát", "Cúc", "Cường", "Cam", "Dao", "Di", "Diem", "Diệp", "Diệu", "Du", "Dung", "Duyên", "Dân", "Dương", "Giang", "Giao", "Hiếu", "Hian", "Hiệp", "Hoa", "Hoan", "Hoài", "Hoàn", "Huyền", "Huệ", "Hà", "Hân", "Ha", "Huong", "Hưng", "Hứa", "Hanh", "Hai", "Hao", "Hậu", "Hằng", "Hang", "Hap", "Khai", "Khanh", "Khuyên", "Khuê", "Khánh", "Khê", "Khôi", "Kim", "Kiều", "Lam", "Lan", "Linh", "Liên", "Linh", "Loan", "Ly", "Lâm", "Lư", "Lê", "La", "Lạc", "Lai", "Mai", "Mi", "Minh", "Miên", "My", "Man", "Ma", "Nga", "Nghi", "Nguyên", "Nguyệt", "Ngà", "Ngân", "Ngôn", "Ngọc", "Nhi", "Nhiên", "Nhung", "Nhàn", "Nhân", "Nhã", "Nhu", "Nuong", "Na", "Oanh", "Phi", "Phong", "Phúc", "Phuong", "Phuc", "Phương", "Phang", "Quyên", "Quân", "Quý", "Quanh", "Sa", "San", "Sinh", "Suong", "Thanh", "Thao", "Thi", "Thiên", "Thiên", "Thoa", "Thoai", "Thu", "Thuần", "Thuan", "Thy", "Thêu", "Thùy", "Thúy", "Tho", "Thu", "Thuong", "Thuơng", "Thọ", "Thơm", "Thục", "Thủy", "Tiên", "Trang", "Trinh", "Trung", "Trà", "Trâm", "Trân", "Trúc", "Tram", "Tuyan", "Tuyếtt", "Tuyên", "Tua", "Ty", "Tâm", "Tú", "Uyên", "Uyen", "Vi", "Việt", "Vy", "Vân", "Vũ", "Vang", "Văn", "Xuyên", "Xuân", "Yên", "Yen", "Ái", "Ánh", " n", "Đan", "Điệp", "Đoan", "Đài", "Đàn", "Đào", "Đ́inh", "Đương", "Đan", "Ư"],
        d = document;
    switch (location.pathname) {
        case "/reg/":
            d.getElementsByName("firstname")[0].value = f[Math.floor(Math.random() * f.length)], d.getElementsByName("lastname")[0].value = l[Math.floor(Math.random() * l.length)], d.getElementsByName("reg_email__")[0].value = "+84973" + Math.floor(888888 * Math.random() + 111111), d.getElementsByName("sex")[0].value = "1", d.getElementsByName("birthday_day")[0].value = "28", d.getElementsByName("birthday_month")[0].value = "06", d.getElementsByName("birthday_year")[0].value = "1996", d.getElementsByName("reg_passwd__")[0].value = "Hungvjp";
            break;
        case "/changeemail":
            d.getElementsByName("new")[0].value = "zz" + Math.floor(888888 * Math.random() + 111111) + "@youremaildomain.com"
    }
})();